### ISSUE TITLE
Browser history saves URL containing UTM

### ISSUE THREAD

**Issue by wefalltomorrow** [mihaip/utm-stripper#12]
This extension works great, but links containing UTM are stored in the history. Would it be possible to change/remove said links to get rid of UTM?

**Comment by mihaip** [comment]
Not without making the extension significantly more invasive (it would need to intercept all navigations and redirect them before Chrome beings the load and thus recording the history entry).

**Comment by wefalltomorrow** [comment]
That's a shame, appreciate the response anyhow.
